# Generated by Django 5.1.7 on 2025-08-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comment",
            name="external_id",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="content.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="external_id",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="user_id",
            field=models.PositiveIntegerField(),
        ),
    ]
