# Generated by Django 5.1.7 on 2025-08-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="user_id",
            field=models.PositiveIntegerField(default=99999942),
        ),
    ]
