version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: dockerfiles/app.dockerfile
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace/src
    env_file:
      - ../.env

    command: sleep infinity
    depends_on:
      - db
  db:
    build:
      context: ..
      dockerfile: dockerfiles/db.dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../.env

volumes:
  postgres-data: